server {
    listen 80;
    server_name epanel-build.com www.epanel-build.com _;
    root /var/www/frontend;
    index index.html;

    client_max_body_size 50M;

    location /api {
        try_files $uri @backend;
    }

    location /up {
        try_files $uri @backend;
    }

    location @backend {
        fastcgi_pass backend:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/backend/public/index.php;
        include fastcgi_params;
        fastcgi_param REQUEST_URI $request_uri;
        fastcgi_param QUERY_STRING $query_string;
        fastcgi_param REQUEST_METHOD $request_method;
        fastcgi_param CONTENT_TYPE $content_type;
        fastcgi_param CONTENT_LENGTH $content_length;
        fastcgi_param HTTP_AUTHORIZATION $http_authorization;
        fastcgi_param HTTPS on;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
