import { Injectable, computed, inject, signal } from '@angular/core';
import {
  Circuit,
  Connection,
  DesignData,
  EnclosureConfig,
  PlacedComponent,
  emptyWiring,
  formatCableType,
  parseCableKind,
} from '../models/project.models';
import { ComponentGroup, EtiProduct } from '../models/catalog.models';
import { WiringService } from './wiring.service';
import { DesignCheckService } from './design-check.service';
import { SchematicService } from './schematic.service';

const DEFAULT_ENCLOSURE: EnclosureConfig = {
  catalogNumber: '001101011',
  name: 'ETIBOX ECT 24 (2x12)',
  rows: 2,
  modulesPerRow: 12,
  supplySystem: 'TN-C-S',
  phases: 3,
  ipRating: 'IP40',
  thermalLimitW: 45,
  ambientTempC: 30,
};

function emptyDesign(): DesignData {
  return {
    enclosure: { ...DEFAULT_ENCLOSURE },
    rows: [0, 1],
    components: [],
    connections: [],
    legend: [],
    manualItems: [],
    wiring: emptyWiring(),
  };
}

function toNumber(value: string | number | null | undefined): number | null {
  if (value === null || value === undefined || value === '') return null;
  const n = typeof value === 'number' ? value : Number(value);
  return Number.isFinite(n) ? n : null;
}

let uidCounter = 0;
function makeUid(): string {
  uidCounter += 1;
  return `c${Date.now().toString(36)}${uidCounter}`;
}

@Injectable({ providedIn: 'root' })
export class DesignStore {
  private readonly wiringService = inject(WiringService);
  private readonly checkService = inject(DesignCheckService);
  private readonly schematicService = inject(SchematicService);

  private readonly _design = signal<DesignData>(emptyDesign());
  private history: DesignData[] = [];
  private future: DesignData[] = [];

  readonly design = this._design.asReadonly();
  readonly components = computed(() => this._design().components);
  readonly enclosure = computed(() => this._design().enclosure);
  readonly canUndo = computed(() => this.historySize() > 0);

  readonly wiring = computed(() => this._design().wiring);
  readonly circuits = computed(() => this._design().wiring.circuits);
  readonly warnings = computed(() => this.checkService.run(this._design()));

  /** Total heat generated by all devices, used for the thermal check. */
  readonly totalHeatW = computed(() =>
    Math.round(
      this._design().components.reduce((sum, c) => sum + (c.heatDissipationW ?? 0), 0) * 10
    ) / 10
  );

  readonly fillPercent = computed(() => {
    const design = this._design();
    const capacity = design.enclosure.rows * design.enclosure.modulesPerRow;
    if (!capacity) return 0;
    const used = design.components.reduce((sum, c) => sum + c.widthModules, 0);
    return Math.round((used / capacity) * 100);
  });

  private historySizeSignal = signal(0);
  private futureSizeSignal = signal(0);
  readonly undoAvailable = this.historySizeSignal.asReadonly();
  readonly redoAvailable = this.futureSizeSignal.asReadonly();

  private historySize(): number {
    return this.history.length;
  }

  load(design: DesignData): void {
    this.history = [];
    this.future = [];
    this._design.set(this.normalise(design));
    this.syncHistorySignals();
  }

  reset(): void {
    this.commit(emptyDesign());
  }

  /**
   * The design as it should be persisted. The single-line diagram is rendered
   * here so the PDF the backend produces always matches the saved layout.
   */
  designForSave(): DesignData {
    const design = this._design();

    return {
      ...design,
      schematicSvg: design.components.length ? this.schematicService.buildSvg(design) : null,
    };
  }

  setEnclosure(config: EnclosureConfig): void {
    const rows = Array.from({ length: config.rows }, (_, i) => i);
    const next = { ...this._design(), enclosure: config, rows };
    // Drop components on now-removed rows.
    next.components = next.components.filter((c) => c.row < config.rows);
    this.commitLayout(next);
  }

  private normalise(design: Partial<DesignData>): DesignData {
    const base = emptyDesign();
    return {
      ...base,
      ...design,
      enclosure: design.enclosure ?? base.enclosure,
      rows:
        design.rows && design.rows.length
          ? design.rows
          : Array.from(
              { length: design.enclosure?.rows ?? base.enclosure.rows },
              (_, i) => i
            ),
      components: design.components ?? [],
      connections: design.connections ?? [],
      legend: design.legend ?? [],
      manualItems: design.manualItems ?? [],
      wiring: design.wiring ?? emptyWiring(),
      schematicSvg: design.schematicSvg ?? null,
    };
  }

  /**
   * Rebuilds wires and busbars. Stored feeds stay unless `inferAll` is set,
   * which throws away manual connections and infers them from layout again.
   */
  generateWiring(inferAll = false): void {
    const design = this._design();
    const components = inferAll
      ? design.components.map((c) => ({
          ...c,
          feedFromUid: undefined,
          omitNeutralDrop: undefined,
          omitPeDrop: undefined,
        }))
      : design.components;
    this.commit(this.applyWiring({ ...design, components }, true));
  }

  /** Rebuild geometry from current positions without changing who feeds whom. */
  rerouteWiring(): void {
    const design = this._design();
    if (!design.wiring.generatedAt) return;
    this.commit(this.applyWiring(design));
  }

  setFeedFrom(uid: string, feedUid: string | null): { ok: boolean; message?: string } {
    const design = this._design();
    if (!design.components.some((c) => c.uid === uid)) {
      return { ok: false, message: 'Апаратът не е намерен.' };
    }
    if (feedUid && !design.components.some((c) => c.uid === feedUid)) {
      return { ok: false, message: 'Източникът не е намерен.' };
    }
    if (this.wouldCycle(design.components, uid, feedUid)) {
      return { ok: false, message: 'Връзката образува цикъл и не може да се създаде.' };
    }

    const components = design.components.map((c) => {
      if (c.uid === uid) return { ...c, feedFromUid: feedUid };
      if (feedUid && c.uid === feedUid && c.feedFromUid === undefined) {
        return { ...c, feedFromUid: null };
      }
      return c;
    });
    this.commit(this.applyWiring({ ...design, components }, false));
    return { ok: true };
  }

  removeWire(wireId: string): boolean {
    const design = this._design();
    const wire = design.wiring.wires.find((w) => w.id === wireId);
    if (!wire) return false;

    const toUid = wire.to.componentUid;
    if (wire.from.componentUid === 'N-BAR') {
      this.commit(
        this.applyWiring({
          ...design,
          components: design.components.map((c) =>
            c.uid === toUid ? { ...c, omitNeutralDrop: true } : c
          ),
        })
      );
      return true;
    }
    if (wire.from.componentUid === 'PE-BAR') {
      this.commit(
        this.applyWiring({
          ...design,
          components: design.components.map((c) =>
            c.uid === toUid ? { ...c, omitPeDrop: true } : c
          ),
        })
      );
      return true;
    }

    return this.setFeedFrom(toUid, null).ok;
  }

  restoreBarDrop(uid: string, conductor: 'N' | 'PE'): void {
    const design = this._design();
    const components = design.components.map((c) => {
      if (c.uid !== uid) return c;
      return conductor === 'N'
        ? { ...c, omitNeutralDrop: undefined }
        : { ...c, omitPeDrop: undefined };
    });
    this.commit(this.applyWiring({ ...design, components }));
  }

  private applyWiring(design: DesignData, inferMissing = !!design.wiring.generatedAt): DesignData {
    const tree = this.wiringService.resolveTree(design, inferMissing);
    const wiring = this.wiringService.materialize(design, tree);
    wiring.circuits = this.mergeCircuitEdits(design.wiring.circuits, wiring.circuits);
    return {
      ...design,
      components: this.wiringService.stampComponents(design.components, tree),
      connections: this.wiringService.connectionsFromTree(tree),
      wiring,
    };
  }

  private mergeCircuitEdits(previous: Circuit[], next: Circuit[]): Circuit[] {
    const byDevice = new Map(previous.map((c) => [c.protectiveDeviceUid, c]));
    return next.map((circuit) => {
      const old = byDevice.get(circuit.protectiveDeviceUid);
      if (!old) return circuit;
      const lengthM = old.lengthM;
      const kind = old.cableKind ?? parseCableKind(old.cableType);
      const mm2 = old.cableCrossSectionMm2;
      const threePhase = circuit.conductors.filter((c) => c.startsWith('L')).length > 1;
      return {
        ...circuit,
        name: old.name,
        description: old.description ?? circuit.description,
        loadKw: old.loadKw,
        lengthM,
        cableKind: kind,
        cableType: formatCableType(kind, circuit.conductors, mm2),
        cableCrossSectionMm2: mm2,
        voltageDropPercent: this.wiringService.voltageDrop(
          threePhase
            ? old.loadKw * 1000 / (Math.sqrt(3) * 400 * old.powerFactor)
            : old.loadKw * 1000 / (230 * old.powerFactor),
          lengthM,
          mm2,
          threePhase
        ),
      };
    });
  }

  private wouldCycle(
    components: PlacedComponent[],
    uid: string,
    feedUid: string | null
  ): boolean {
    if (!feedUid) return false;
    if (feedUid === uid) return true;
    const byUid = new Map(components.map((c) => [c.uid, c]));
    const seen = new Set<string>();
    let current: string | null | undefined = feedUid;
    while (current) {
      if (current === uid) return true;
      if (seen.has(current)) return true;
      seen.add(current);
      current = byUid.get(current)?.feedFromUid;
    }
    return false;
  }

  private commitLayout(next: DesignData): void {
    this.commit(next.wiring.generatedAt ? this.applyWiring(next) : next);
  }

  updateCircuit(id: string, patch: Partial<Circuit>): void {
    const design = this._design();
    const circuits = design.wiring.circuits.map((circuit) => {
      if (circuit.id !== id) return circuit;
      const merged = { ...circuit, ...patch };
      const threePhase = merged.conductors.filter((c) => c.startsWith('L')).length > 1;
      const voltage = threePhase ? 400 : 230;
      const current =
        (merged.loadKw * 1000) / ((threePhase ? Math.sqrt(3) : 1) * voltage * merged.powerFactor);
      const kind = merged.cableKind ?? parseCableKind(merged.cableType);
      return {
        ...merged,
        cableKind: kind,
        cableType: formatCableType(kind, merged.conductors, merged.cableCrossSectionMm2),
        voltageDropPercent: this.wiringService.voltageDrop(
          current,
          merged.lengthM,
          merged.cableCrossSectionMm2,
          threePhase
        ),
      };
    });
    this.commit({ ...design, wiring: { ...design.wiring, circuits } });
  }

  clearWiring(): void {
    const design = this._design();
    this.commit({
      ...design,
      connections: [],
      components: design.components.map((c) => ({
        ...c,
        feedFromUid: undefined,
        omitNeutralDrop: undefined,
        omitPeDrop: undefined,
      })),
      wiring: emptyWiring(),
    });
  }

  /** Find the first free slot that fits `width` modules on any row. */
  findFreeSlot(width: number): { row: number; startModule: number } | null {
    const design = this._design();
    for (let row = 0; row < design.enclosure.rows; row++) {
      const slot = this.firstFreeInRow(row, width);
      if (slot !== null) {
        return { row, startModule: slot };
      }
    }
    return null;
  }

  private firstFreeInRow(row: number, width: number, ignoreUid?: string): number | null {
    const design = this._design();
    const occupied = new Array(design.enclosure.modulesPerRow).fill(false);
    for (const c of design.components) {
      if (c.row !== row || c.uid === ignoreUid) continue;
      for (let m = c.startModule; m < c.startModule + c.widthModules; m++) {
        if (m >= 0 && m < occupied.length) occupied[m] = true;
      }
    }
    for (let start = 0; start + width <= occupied.length; start++) {
      let fits = true;
      for (let m = start; m < start + width; m++) {
        if (occupied[m]) {
          fits = false;
          break;
        }
      }
      if (fits) return start;
    }
    return null;
  }

  canPlace(row: number, startModule: number, width: number, ignoreUid?: string): boolean {
    const design = this._design();
    if (row < 0 || row >= design.enclosure.rows) return false;
    if (startModule < 0 || startModule + width > design.enclosure.modulesPerRow) return false;
    for (const c of design.components) {
      if (c.row !== row || c.uid === ignoreUid) continue;
      const overlap =
        startModule < c.startModule + c.widthModules && startModule + width > c.startModule;
      if (overlap) return false;
    }
    return true;
  }

  addProduct(product: EtiProduct, label?: string): PlacedComponent | null {
    const width = Math.max(1, product.width_modules || 1);
    const slot = this.findFreeSlot(width);
    if (!slot) return null;

    const component: PlacedComponent = {
      ...this.electricalAttributes(product),
      uid: makeUid(),
      catalogNumber: product.catalog_number,
      name: product.name,
      label: label ?? this.nextLabel(product),
      series: product.series,
      row: slot.row,
      startModule: slot.startModule,
      widthModules: width,
      verified: product.verified,
    };

    const next = { ...this._design(), components: [...this._design().components, component] };
    this.commitLayout(next);
    return component;
  }

  /** Electrical data copied onto the placed component so wiring works offline. */
  private electricalAttributes(product?: EtiProduct): Partial<PlacedComponent> {
    return {
      category: product?.category ?? null,
      poles: product?.poles ?? 1,
      ratedCurrentA: toNumber(product?.rated_current_a),
      residualCurrentA: toNumber(product?.residual_current_a),
      tripCurve: product?.trip_curve ?? null,
      heatDissipationW: toNumber(product?.heat_dissipation_w),
    };
  }

  addGroup(group: ComponentGroup, products: Map<string, EtiProduct>): boolean {
    const groupWidth = group.items.reduce((max, item) => {
      const product = products.get(item.catalog_number);
      const width = Math.max(1, product?.width_modules || 1);
      return Math.max(max, item.offset_module + width);
    }, 0);

    const slot = this.findFreeSlot(groupWidth);
    if (!slot) return false;

    const groupId = makeUid();
    const newComponents: PlacedComponent[] = group.items.map((item) => {
      const product = products.get(item.catalog_number);
      return {
        ...this.electricalAttributes(product),
        uid: makeUid(),
        catalogNumber: item.catalog_number,
        name: product?.name ?? item.catalog_number,
        label: item.label,
        series: product?.series ?? null,
        row: slot.row,
        startModule: slot.startModule + item.offset_module,
        widthModules: Math.max(1, product?.width_modules || 1),
        groupId,
        verified: product?.verified ?? false,
      };
    });

    const labelToUid = new Map(newComponents.map((c) => [c.label, c.uid]));
    const newConnections: Connection[] = (group.connections ?? [])
      .map((conn) => ({
        from: labelToUid.get(conn.from) ?? conn.from,
        to: labelToUid.get(conn.to) ?? conn.to,
        type: conn.type,
      }))
      .filter((c) => c.from && c.to);

    const fed = newComponents.map((comp) => {
      const feed = newConnections.find((conn) => conn.to === comp.uid);
      return feed ? { ...comp, feedFromUid: feed.from } : comp;
    });

    const design = this._design();
    this.commitLayout({
      ...design,
      components: [...design.components, ...fed],
      connections: [...design.connections, ...newConnections],
    });
    return true;
  }

  moveComponent(uid: string, row: number, startModule: number): boolean {
    const component = this._design().components.find((c) => c.uid === uid);
    if (!component) return false;

    if (component.groupId) {
      return this.moveGroup(component.groupId, uid, row, startModule);
    }

    if (!this.canPlace(row, startModule, component.widthModules, uid)) return false;

    const next = {
      ...this._design(),
      components: this._design().components.map((c) =>
        c.uid === uid ? { ...c, row, startModule } : c
      ),
    };
    this.commitLayout(next);
    return true;
  }

  private moveGroup(groupId: string, anchorUid: string, row: number, startModule: number): boolean {
    const design = this._design();
    const anchor = design.components.find((c) => c.uid === anchorUid);
    if (!anchor) return false;

    const deltaRow = row - anchor.row;
    const deltaModule = startModule - anchor.startModule;
    const members = design.components.filter((c) => c.groupId === groupId);
    const memberUids = new Set(members.map((c) => c.uid));

    for (const member of members) {
      const targetRow = member.row + deltaRow;
      const targetModule = member.startModule + deltaModule;
      if (!this.canPlaceIgnoring(targetRow, targetModule, member.widthModules, memberUids)) {
        return false;
      }
    }

    const next = {
      ...design,
      components: design.components.map((c) =>
        c.groupId === groupId
          ? { ...c, row: c.row + deltaRow, startModule: c.startModule + deltaModule }
          : c
      ),
    };
    this.commitLayout(next);
    return true;
  }

  private canPlaceIgnoring(
    row: number,
    startModule: number,
    width: number,
    ignoreUids: Set<string>
  ): boolean {
    const design = this._design();
    if (row < 0 || row >= design.enclosure.rows) return false;
    if (startModule < 0 || startModule + width > design.enclosure.modulesPerRow) return false;
    for (const c of design.components) {
      if (c.row !== row || ignoreUids.has(c.uid)) continue;
      const overlap =
        startModule < c.startModule + c.widthModules && startModule + width > c.startModule;
      if (overlap) return false;
    }
    return true;
  }

  removeComponent(uid: string): void {
    const design = this._design();
    const component = design.components.find((c) => c.uid === uid);
    if (!component) return;

    const removeUids = component.groupId
      ? new Set(design.components.filter((c) => c.groupId === component.groupId).map((c) => c.uid))
      : new Set([uid]);

    this.commitLayout({
      ...design,
      components: design.components.filter((c) => !removeUids.has(c.uid)),
      connections: design.connections.filter(
        (conn) => !removeUids.has(conn.from) && !removeUids.has(conn.to)
      ),
    });
  }

  updateLabel(uid: string, label: string): void {
    const next = {
      ...this._design(),
      components: this._design().components.map((c) =>
        c.uid === uid ? { ...c, label } : c
      ),
    };
    this.commit(next);
  }

  autoArrange(): void {
    const design = this._design();
    const sorted = [...design.components].sort(
      (a, b) => (b.widthModules - a.widthModules) || a.label.localeCompare(b.label)
    );
    const cleared: PlacedComponent[] = [];
    const working = { ...design, components: cleared };
    this._design.set(working);

    for (const comp of sorted) {
      const slot = this.findFreeSlot(comp.widthModules);
      if (slot) {
        cleared.push({ ...comp, row: slot.row, startModule: slot.startModule });
        this._design.set({ ...working, components: [...cleared] });
      } else {
        cleared.push(comp);
      }
    }
    this.commitLayout({ ...design, components: cleared });
  }

  setLegend(legend: DesignData['legend']): void {
    this.commit({ ...this._design(), legend });
  }

  setManualItems(items: DesignData['manualItems']): void {
    this.commit({ ...this._design(), manualItems: items });
  }

  undo(): void {
    if (!this.history.length) return;
    const prev = this.history.pop()!;
    this.future.push(this._design());
    this._design.set(prev);
    this.syncHistorySignals();
  }

  redo(): void {
    if (!this.future.length) return;
    const next = this.future.pop()!;
    this.history.push(this._design());
    this._design.set(next);
    this.syncHistorySignals();
  }

  private commit(next: DesignData): void {
    this.history.push(this._design());
    if (this.history.length > 50) this.history.shift();
    this.future = [];
    this._design.set(next);
    this.syncHistorySignals();
  }

  private syncHistorySignals(): void {
    this.historySizeSignal.set(this.history.length);
    this.futureSizeSignal.set(this.future.length);
  }

  private nextLabel(product: EtiProduct): string {
    const prefix = this.labelPrefix(product);
    const existing = this._design()
      .components.map((c) => c.label)
      .filter((l) => l.startsWith(prefix));
    let n = 1;
    while (existing.includes(`${prefix}${n}`)) n++;
    return `${prefix}${n}`;
  }

  private labelPrefix(product: EtiProduct): string {
    const category = (product.category ?? '').toUpperCase();
    if (category.includes('RCD') || category.includes('RCBO')) return 'FI';
    if (category.includes('MCB') || category.includes('MCCB')) return 'F';
    if (category.includes('CONTACTOR')) return 'K';
    if (category.includes('SWITCH')) return 'Q';
    if (category.includes('SPD')) return 'SPD';
    return 'X';
  }
}
